(() => {
  const common = {
    en: {
      skip: "Skip to content", home: "Home", privacy: "Privacy", terms: "Terms", language: "Language", legal: "Legal",
      updated: "Last updated: July 30, 2026", development_label: "Development status.", translation_label: "Translations.",
      translation_notice: "Translations are provided for convenience. If versions differ during private development, the English version controls.",
      trademark: "The term “Etsy” is a trademark of Etsy, Inc. This application uses the Etsy API but is not endorsed or certified by Etsy, Inc."
    },
    it: {
      skip: "Vai al contenuto", home: "Home", privacy: "Privacy", terms: "Termini", language: "Lingua", legal: "Informazioni legali",
      updated: "Ultimo aggiornamento: 30 luglio 2026", development_label: "Stato di sviluppo.", translation_label: "Traduzioni.",
      translation_notice: "Le traduzioni sono fornite per comodità. In caso di differenze durante lo sviluppo privato, prevale la versione inglese.",
      trademark: "Il termine “Etsy” è un marchio di Etsy, Inc. Questa applicazione utilizza l’API di Etsy, ma non è approvata né certificata da Etsy, Inc."
    },
    es: {
      skip: "Ir al contenido", home: "Inicio", privacy: "Privacidad", terms: "Términos", language: "Idioma", legal: "Información legal",
      updated: "Última actualización: 30 de julio de 2026", development_label: "Estado de desarrollo.", translation_label: "Traducciones.",
      translation_notice: "Las traducciones se ofrecen por comodidad. Si existen diferencias durante el desarrollo privado, prevalece la versión inglesa.",
      trademark: "El término “Etsy” es una marca comercial de Etsy, Inc. Esta aplicación utiliza la API de Etsy, pero no está respaldada ni certificada por Etsy, Inc."
    },
    fr: {
      skip: "Aller au contenu", home: "Accueil", privacy: "Confidentialité", terms: "Conditions", language: "Langue", legal: "Informations légales",
      updated: "Dernière mise à jour : 30 juillet 2026", development_label: "État du développement.", translation_label: "Traductions.",
      translation_notice: "Les traductions sont fournies pour faciliter la lecture. En cas de divergence pendant le développement privé, la version anglaise prévaut.",
      trademark: "Le terme « Etsy » est une marque d’Etsy, Inc. Cette application utilise l’API Etsy mais n’est ni approuvée ni certifiée par Etsy, Inc."
    },
    de: {
      skip: "Zum Inhalt", home: "Startseite", privacy: "Datenschutz", terms: "Nutzungsbedingungen", language: "Sprache", legal: "Rechtliches",
      updated: "Letzte Aktualisierung: 30. Juli 2026", development_label: "Entwicklungsstatus.", translation_label: "Übersetzungen.",
      translation_notice: "Übersetzungen dienen der leichteren Lesbarkeit. Bei Abweichungen während der privaten Entwicklung ist die englische Fassung maßgeblich.",
      trademark: "Der Begriff „Etsy“ ist eine Marke von Etsy, Inc. Diese Anwendung verwendet die Etsy-API, wird jedoch nicht von Etsy, Inc. unterstützt oder zertifiziert."
    }
  };

  const pages = {
    privacy: {
      en: {
        pageTitle: "Privacy Policy — Veylto", metaDescription: "Veylto Privacy Policy.", privacy_title: "Privacy Policy",
        privacy_development: "Veylto is currently in private development. This policy describes the intended handling of information during controlled testing and will be reviewed before public release.",
        privacy_h1: "1. Overview", privacy_p1: "Veylto is a local-first desktop application developed under the independent Veylto Labs product brand. It is intended to help Etsy sellers manage authorized shop workflows. This policy explains what information may be processed, why it is used and the choices available to users.",
        privacy_h2: "2. Information processed", privacy_p2: "Depending on the features used, Veylto may process:",
        privacy_li21: "account and shop identifiers returned through Etsy OAuth;", privacy_li22: "listing, inventory, order and shop performance data authorized by the user;", privacy_li23: "product images, mockups, prompts and other content submitted for AI-assisted workflows;", privacy_li24: "application settings, workflow history and locally generated reports;", privacy_li25: "technical diagnostics needed to operate, secure or troubleshoot the application.",
        privacy_h3: "3. Etsy authorization", privacy_p3: "Private Etsy data is accessed only after the seller authorizes the requested permissions through Etsy OAuth. Veylto does not ask users to share Etsy passwords or API credentials. Access can be revoked through the relevant Etsy account controls and, where available, through Veylto.",
        privacy_h4: "4. Purpose of processing", privacy_p4: "Information is processed to provide requested features, analyze seller-provided images and mockups, generate and validate AI-assisted listing content, display shop data, prepare seller-reviewed changes, generate reports, maintain application state, diagnose failures and protect the service from misuse.",
        privacy_h5: "5. Local storage and service infrastructure", privacy_p5: "Veylto is designed around a desktop application and local workflow storage. Some production functions may require secure service infrastructure, including OAuth coordination, credential protection, licensing, rate limiting and controlled Etsy API access. Final production architecture and retention periods will be documented before public release.",
        privacy_h6: "6. AI providers", privacy_p6: "When a user selects an external AI provider, relevant input may be sent to that provider to complete the requested task. This may include text, product context, images or mockups selected by the user. Provider processing is governed by the provider’s own terms and privacy practices. Veylto is designed to show the selected provider and model rather than silently substituting another provider.",
        privacy_h7: "7. Sharing", privacy_p7: "Veylto does not sell personal information. Information may be shared only with service providers needed to deliver requested functionality, comply with law, protect rights and security, or complete a business transition subject to appropriate safeguards.",
        privacy_h8: "8. Retention and deletion", privacy_p8: "Locally stored information remains under the user’s control unless a feature states otherwise. Service-side information, where required, will be retained only for the period necessary for operation, security, legal compliance and dispute resolution. Users may request deletion of service-side personal information by contacting support.",
        privacy_h9: "9. Security", privacy_p9: "Reasonable technical and organizational measures are used or planned to protect information. No system can guarantee absolute security. Users remain responsible for protecting their device, account access, provider credentials and local backups.",
        privacy_h10: "10. International processing", privacy_p10: "Service providers may process information in countries other than the user’s country. Appropriate safeguards will be used where required by applicable law.",
        privacy_h11: "11. User rights", privacy_p11: "Depending on location, users may have rights to access, correct, delete, restrict or object to processing of personal information. Requests can be sent to",
        privacy_h12: "12. Changes", privacy_p12: "This policy may be updated as Veylto’s production architecture and features are finalized. The latest version will be published on this page with a revised date.",
        privacy_h13: "13. Contact", privacy_p13: "Privacy questions may be sent to"
      },
      it: {
        pageTitle: "Informativa sulla privacy — Veylto", metaDescription: "Informativa sulla privacy di Veylto.", privacy_title: "Informativa sulla privacy",
        privacy_development: "Veylto è attualmente in sviluppo privato. Questa informativa descrive la gestione prevista delle informazioni durante i test controllati e sarà riesaminata prima del rilascio pubblico.",
        privacy_h1: "1. Panoramica", privacy_p1: "Veylto è un’applicazione desktop local-first sviluppata sotto il marchio di prodotto indipendente Veylto Labs. È destinata ad aiutare i venditori Etsy a gestire workflow autorizzati del negozio. Questa informativa spiega quali informazioni possono essere trattate, per quali finalità e quali scelte sono disponibili agli utenti.",
        privacy_h2: "2. Informazioni trattate", privacy_p2: "A seconda delle funzionalità utilizzate, Veylto può trattare:",
        privacy_li21: "identificativi dell’account e del negozio restituiti tramite Etsy OAuth;", privacy_li22: "dati relativi a inserzioni, inventario, ordini e prestazioni del negozio autorizzati dall’utente;", privacy_li23: "immagini di prodotto, mockup, prompt e altri contenuti inviati per workflow assistiti dall’AI;", privacy_li24: "impostazioni dell’applicazione, cronologia dei workflow e report generati localmente;", privacy_li25: "diagnostica tecnica necessaria per utilizzare, proteggere o risolvere problemi dell’applicazione.",
        privacy_h3: "3. Autorizzazione Etsy", privacy_p3: "I dati privati di Etsy vengono consultati solo dopo che il venditore ha autorizzato i permessi richiesti tramite Etsy OAuth. Veylto non chiede agli utenti di condividere password Etsy o credenziali API. L’accesso può essere revocato tramite i relativi controlli dell’account Etsy e, quando disponibile, tramite Veylto.",
        privacy_h4: "4. Finalità del trattamento", privacy_p4: "Le informazioni vengono trattate per fornire le funzionalità richieste, analizzare immagini e mockup forniti dal venditore, generare e validare contenuti di inserzioni assistiti dall’AI, mostrare dati del negozio, preparare modifiche revisionate dal venditore, generare report, mantenere lo stato dell’applicazione, diagnosticare errori e proteggere il servizio da usi impropri.",
        privacy_h5: "5. Archiviazione locale e infrastruttura del servizio", privacy_p5: "Veylto è progettato attorno a un’applicazione desktop e all’archiviazione locale dei workflow. Alcune funzioni di produzione possono richiedere un’infrastruttura sicura, inclusi coordinamento OAuth, protezione delle credenziali, licenze, limiti di frequenza e accesso controllato all’API Etsy. L’architettura finale di produzione e i periodi di conservazione saranno documentati prima del rilascio pubblico.",
        privacy_h6: "6. Provider AI", privacy_p6: "Quando un utente seleziona un provider AI esterno, gli input pertinenti possono essere inviati a tale provider per completare l’attività richiesta. Possono includere testo, contesto del prodotto, immagini o mockup selezionati dall’utente. Il trattamento del provider è regolato dai relativi termini e pratiche sulla privacy. Veylto è progettato per mostrare il provider e il modello selezionati, senza sostituirli in modo silenzioso.",
        privacy_h7: "7. Condivisione", privacy_p7: "Veylto non vende informazioni personali. Le informazioni possono essere condivise solo con fornitori di servizi necessari per erogare le funzionalità richieste, rispettare la legge, proteggere diritti e sicurezza o completare una transizione aziendale con garanzie adeguate.",
        privacy_h8: "8. Conservazione e cancellazione", privacy_p8: "Le informazioni archiviate localmente restano sotto il controllo dell’utente, salvo diversa indicazione di una funzionalità. Le informazioni lato servizio, quando necessarie, saranno conservate solo per il periodo richiesto da operatività, sicurezza, obblighi legali e gestione delle controversie. Gli utenti possono richiedere la cancellazione delle informazioni personali lato servizio contattando il supporto.",
        privacy_h9: "9. Sicurezza", privacy_p9: "Sono adottate o pianificate misure tecniche e organizzative ragionevoli per proteggere le informazioni. Nessun sistema può garantire sicurezza assoluta. Gli utenti restano responsabili della protezione del dispositivo, dell’accesso agli account, delle credenziali dei provider e dei backup locali.",
        privacy_h10: "10. Trattamento internazionale", privacy_p10: "I fornitori di servizi possono trattare informazioni in Paesi diversi da quello dell’utente. Saranno utilizzate garanzie adeguate quando richiesto dalla legge applicabile.",
        privacy_h11: "11. Diritti dell’utente", privacy_p11: "In base al luogo di residenza, gli utenti possono avere il diritto di accedere, correggere, cancellare, limitare o opporsi al trattamento delle informazioni personali. Le richieste possono essere inviate a",
        privacy_h12: "12. Modifiche", privacy_p12: "Questa informativa può essere aggiornata mentre vengono definite l’architettura di produzione e le funzionalità di Veylto. La versione più recente sarà pubblicata su questa pagina con una data aggiornata.",
        privacy_h13: "13. Contatti", privacy_p13: "Le domande sulla privacy possono essere inviate a"
      },
      es: {
        pageTitle: "Política de privacidad — Veylto", metaDescription: "Política de privacidad de Veylto.", privacy_title: "Política de privacidad",
        privacy_development: "Veylto se encuentra actualmente en desarrollo privado. Esta política describe el tratamiento previsto de la información durante las pruebas controladas y será revisada antes del lanzamiento público.",
        privacy_h1: "1. Resumen", privacy_p1: "Veylto es una aplicación de escritorio local-first desarrollada bajo la marca de producto independiente Veylto Labs. Está destinada a ayudar a los vendedores de Etsy a gestionar flujos autorizados de su tienda. Esta política explica qué información puede tratarse, por qué se utiliza y qué opciones tienen los usuarios.",
        privacy_h2: "2. Información tratada", privacy_p2: "Según las funciones utilizadas, Veylto puede tratar:",
        privacy_li21: "identificadores de cuenta y tienda devueltos mediante Etsy OAuth;", privacy_li22: "datos de publicaciones, inventario, pedidos y rendimiento de la tienda autorizados por el usuario;", privacy_li23: "imágenes de producto, mockups, prompts y otros contenidos enviados para flujos asistidos por IA;", privacy_li24: "ajustes de la aplicación, historial de flujos e informes generados localmente;", privacy_li25: "diagnósticos técnicos necesarios para operar, proteger o solucionar problemas de la aplicación.",
        privacy_h3: "3. Autorización de Etsy", privacy_p3: "Los datos privados de Etsy solo se consultan después de que el vendedor autorice los permisos solicitados mediante Etsy OAuth. Veylto no pide a los usuarios que compartan contraseñas de Etsy ni credenciales API. El acceso puede revocarse desde los controles correspondientes de la cuenta de Etsy y, cuando esté disponible, desde Veylto.",
        privacy_h4: "4. Finalidad del tratamiento", privacy_p4: "La información se trata para ofrecer las funciones solicitadas, analizar imágenes y mockups aportados por el vendedor, generar y validar contenido de publicaciones asistido por IA, mostrar datos de la tienda, preparar cambios revisados por el vendedor, generar informes, mantener el estado de la aplicación, diagnosticar fallos y proteger el servicio frente a usos indebidos.",
        privacy_h5: "5. Almacenamiento local e infraestructura del servicio", privacy_p5: "Veylto se diseña en torno a una aplicación de escritorio y al almacenamiento local de los flujos. Algunas funciones de producción pueden requerir infraestructura segura, incluida la coordinación OAuth, protección de credenciales, licencias, límites de frecuencia y acceso controlado a la API de Etsy. La arquitectura final de producción y los periodos de conservación se documentarán antes del lanzamiento público.",
        privacy_h6: "6. Proveedores de IA", privacy_p6: "Cuando el usuario selecciona un proveedor externo de IA, los datos pertinentes pueden enviarse a ese proveedor para completar la tarea solicitada. Esto puede incluir texto, contexto del producto, imágenes o mockups seleccionados por el usuario. El tratamiento del proveedor se rige por sus propios términos y prácticas de privacidad. Veylto está diseñado para mostrar el proveedor y el modelo seleccionados en lugar de sustituirlos silenciosamente.",
        privacy_h7: "7. Compartición", privacy_p7: "Veylto no vende información personal. La información solo puede compartirse con proveedores necesarios para ofrecer la funcionalidad solicitada, cumplir la ley, proteger derechos y seguridad o completar una transición empresarial sujeta a garantías adecuadas.",
        privacy_h8: "8. Conservación y eliminación", privacy_p8: "La información almacenada localmente permanece bajo el control del usuario salvo que una función indique lo contrario. La información del servicio, cuando sea necesaria, se conservará solo durante el periodo requerido para operación, seguridad, cumplimiento legal y resolución de disputas. Los usuarios pueden solicitar la eliminación de la información personal del servicio contactando con soporte.",
        privacy_h9: "9. Seguridad", privacy_p9: "Se utilizan o planifican medidas técnicas y organizativas razonables para proteger la información. Ningún sistema puede garantizar una seguridad absoluta. Los usuarios siguen siendo responsables de proteger su dispositivo, acceso a cuentas, credenciales de proveedores y copias de seguridad locales.",
        privacy_h10: "10. Tratamiento internacional", privacy_p10: "Los proveedores pueden tratar información en países distintos del país del usuario. Se aplicarán garantías adecuadas cuando lo exija la legislación aplicable.",
        privacy_h11: "11. Derechos del usuario", privacy_p11: "Según su ubicación, los usuarios pueden tener derecho a acceder, corregir, eliminar, limitar u oponerse al tratamiento de información personal. Las solicitudes pueden enviarse a",
        privacy_h12: "12. Cambios", privacy_p12: "Esta política puede actualizarse a medida que se finalicen la arquitectura de producción y las funciones de Veylto. La versión más reciente se publicará en esta página con una fecha revisada.",
        privacy_h13: "13. Contacto", privacy_p13: "Las preguntas sobre privacidad pueden enviarse a"
      },
      fr: {
        pageTitle: "Politique de confidentialité — Veylto", metaDescription: "Politique de confidentialité de Veylto.", privacy_title: "Politique de confidentialité",
        privacy_development: "Veylto est actuellement en développement privé. Cette politique décrit le traitement prévu des informations pendant les tests contrôlés et sera réexaminée avant la mise à disposition publique.",
        privacy_h1: "1. Présentation", privacy_p1: "Veylto est une application desktop local-first développée sous la marque produit indépendante Veylto Labs. Elle vise à aider les vendeurs Etsy à gérer les workflows autorisés de leur boutique. Cette politique explique quelles informations peuvent être traitées, pourquoi elles sont utilisées et quels choix sont proposés aux utilisateurs.",
        privacy_h2: "2. Informations traitées", privacy_p2: "Selon les fonctionnalités utilisées, Veylto peut traiter :",
        privacy_li21: "les identifiants de compte et de boutique retournés via Etsy OAuth ;", privacy_li22: "les données de fiches, d’inventaire, de commandes et de performance de boutique autorisées par l’utilisateur ;", privacy_li23: "les images produit, mockups, prompts et autres contenus transmis pour des workflows assistés par IA ;", privacy_li24: "les paramètres de l’application, l’historique des workflows et les rapports générés localement ;", privacy_li25: "les diagnostics techniques nécessaires au fonctionnement, à la sécurité ou au dépannage de l’application.",
        privacy_h3: "3. Autorisation Etsy", privacy_p3: "Les données privées Etsy ne sont consultées qu’après autorisation des permissions demandées par le vendeur via Etsy OAuth. Veylto ne demande pas aux utilisateurs de partager leurs mots de passe Etsy ni leurs identifiants API. L’accès peut être révoqué depuis les contrôles du compte Etsy et, lorsqu’elle est disponible, depuis Veylto.",
        privacy_h4: "4. Finalités du traitement", privacy_p4: "Les informations sont traitées pour fournir les fonctionnalités demandées, analyser les images et mockups fournis par le vendeur, générer et valider du contenu de fiche assisté par IA, afficher les données de boutique, préparer les modifications vérifiées par le vendeur, produire des rapports, maintenir l’état de l’application, diagnostiquer les incidents et protéger le service contre les usages abusifs.",
        privacy_h5: "5. Stockage local et infrastructure du service", privacy_p5: "Veylto est conçu autour d’une application desktop et du stockage local des workflows. Certaines fonctions de production peuvent nécessiter une infrastructure sécurisée, notamment pour la coordination OAuth, la protection des identifiants, les licences, la limitation du débit et l’accès contrôlé à l’API Etsy. L’architecture finale de production et les durées de conservation seront documentées avant la mise à disposition publique.",
        privacy_h6: "6. Fournisseurs d’IA", privacy_p6: "Lorsqu’un utilisateur sélectionne un fournisseur d’IA externe, les données pertinentes peuvent lui être envoyées pour effectuer la tâche demandée. Elles peuvent inclure du texte, le contexte produit, des images ou des mockups sélectionnés par l’utilisateur. Le traitement du fournisseur est régi par ses propres conditions et pratiques de confidentialité. Veylto est conçu pour afficher le fournisseur et le modèle sélectionnés plutôt que de les remplacer silencieusement.",
        privacy_h7: "7. Partage", privacy_p7: "Veylto ne vend pas les informations personnelles. Les informations ne peuvent être partagées qu’avec les prestataires nécessaires à la fonctionnalité demandée, au respect de la loi, à la protection des droits et de la sécurité ou à une transition d’activité assortie de garanties appropriées.",
        privacy_h8: "8. Conservation et suppression", privacy_p8: "Les informations stockées localement restent sous le contrôle de l’utilisateur, sauf indication contraire d’une fonctionnalité. Les informations côté service, lorsqu’elles sont nécessaires, ne seront conservées que pendant la durée requise pour le fonctionnement, la sécurité, les obligations légales et le règlement des litiges. Les utilisateurs peuvent demander la suppression des informations personnelles côté service en contactant le support.",
        privacy_h9: "9. Sécurité", privacy_p9: "Des mesures techniques et organisationnelles raisonnables sont utilisées ou prévues pour protéger les informations. Aucun système ne peut garantir une sécurité absolue. Les utilisateurs restent responsables de la protection de leur appareil, de l’accès aux comptes, des identifiants des fournisseurs et des sauvegardes locales.",
        privacy_h10: "10. Traitement international", privacy_p10: "Les prestataires peuvent traiter les informations dans des pays autres que celui de l’utilisateur. Des garanties appropriées seront appliquées lorsque la loi l’exige.",
        privacy_h11: "11. Droits des utilisateurs", privacy_p11: "Selon leur lieu de résidence, les utilisateurs peuvent disposer de droits d’accès, de rectification, de suppression, de limitation ou d’opposition au traitement des informations personnelles. Les demandes peuvent être envoyées à",
        privacy_h12: "12. Modifications", privacy_p12: "Cette politique peut être mise à jour au fur et à mesure de la finalisation de l’architecture de production et des fonctionnalités de Veylto. La version la plus récente sera publiée sur cette page avec une date mise à jour.",
        privacy_h13: "13. Contact", privacy_p13: "Les questions relatives à la confidentialité peuvent être envoyées à"
      },
      de: {
        pageTitle: "Datenschutzerklärung — Veylto", metaDescription: "Datenschutzerklärung von Veylto.", privacy_title: "Datenschutzerklärung",
        privacy_development: "Veylto befindet sich derzeit in privater Entwicklung. Diese Erklärung beschreibt den vorgesehenen Umgang mit Informationen während kontrollierter Tests und wird vor der öffentlichen Veröffentlichung überprüft.",
        privacy_h1: "1. Überblick", privacy_p1: "Veylto ist eine Local-first-Desktop-Anwendung, die unter der unabhängigen Produktmarke Veylto Labs entwickelt wird. Sie soll Etsy-Sellern bei der Verwaltung autorisierter Shop-Workflows helfen. Diese Erklärung erläutert, welche Informationen verarbeitet werden können, warum sie verwendet werden und welche Wahlmöglichkeiten Nutzer haben.",
        privacy_h2: "2. Verarbeitete Informationen", privacy_p2: "Je nach verwendeter Funktion kann Veylto Folgendes verarbeiten:",
        privacy_li21: "Konto- und Shop-Kennungen, die über Etsy OAuth zurückgegeben werden;", privacy_li22: "vom Nutzer autorisierte Listing-, Inventar-, Bestell- und Shop-Leistungsdaten;", privacy_li23: "Produktbilder, Mockups, Prompts und andere für KI-gestützte Workflows übermittelte Inhalte;", privacy_li24: "Anwendungseinstellungen, Workflow-Verlauf und lokal erzeugte Berichte;", privacy_li25: "technische Diagnosedaten, die für Betrieb, Sicherheit oder Fehlerbehebung erforderlich sind.",
        privacy_h3: "3. Etsy-Autorisierung", privacy_p3: "Private Etsy-Daten werden erst abgerufen, nachdem der Seller die angeforderten Berechtigungen über Etsy OAuth erteilt hat. Veylto fordert Nutzer nicht zur Weitergabe von Etsy-Passwörtern oder API-Zugangsdaten auf. Der Zugriff kann über die entsprechenden Etsy-Kontoeinstellungen und, sofern verfügbar, über Veylto widerrufen werden.",
        privacy_h4: "4. Zweck der Verarbeitung", privacy_p4: "Informationen werden verarbeitet, um angeforderte Funktionen bereitzustellen, vom Seller bereitgestellte Bilder und Mockups zu analysieren, KI-gestützte Listing-Inhalte zu erzeugen und zu validieren, Shop-Daten anzuzeigen, vom Seller geprüfte Änderungen vorzubereiten, Berichte zu erstellen, den Anwendungsstatus zu verwalten, Fehler zu diagnostizieren und den Dienst vor Missbrauch zu schützen.",
        privacy_h5: "5. Lokale Speicherung und Dienstinfrastruktur", privacy_p5: "Veylto ist als Desktop-Anwendung mit lokaler Workflow-Speicherung konzipiert. Einige Produktionsfunktionen können eine sichere Infrastruktur erfordern, darunter OAuth-Koordination, Schutz von Zugangsdaten, Lizenzierung, Ratenbegrenzung und kontrollierter Etsy-API-Zugriff. Die endgültige Produktionsarchitektur und Aufbewahrungsfristen werden vor der öffentlichen Veröffentlichung dokumentiert.",
        privacy_h6: "6. KI-Provider", privacy_p6: "Wenn ein Nutzer einen externen KI-Provider auswählt, können relevante Eingaben an diesen Provider gesendet werden, um die angeforderte Aufgabe auszuführen. Dazu können Text, Produktkontext, Bilder oder vom Nutzer ausgewählte Mockups gehören. Die Verarbeitung durch den Provider unterliegt dessen eigenen Bedingungen und Datenschutzpraktiken. Veylto ist darauf ausgelegt, den ausgewählten Provider und das Modell anzuzeigen, anstatt sie stillschweigend zu ersetzen.",
        privacy_h7: "7. Weitergabe", privacy_p7: "Veylto verkauft keine personenbezogenen Informationen. Informationen dürfen nur an Dienstleister weitergegeben werden, die für die angeforderte Funktion, die Einhaltung gesetzlicher Pflichten, den Schutz von Rechten und Sicherheit oder eine Geschäftstransaktion mit angemessenen Schutzmaßnahmen erforderlich sind.",
        privacy_h8: "8. Aufbewahrung und Löschung", privacy_p8: "Lokal gespeicherte Informationen bleiben unter der Kontrolle des Nutzers, sofern eine Funktion nichts anderes angibt. Dienstseitige Informationen werden, soweit erforderlich, nur so lange aufbewahrt, wie es für Betrieb, Sicherheit, gesetzliche Pflichten und Streitbeilegung notwendig ist. Nutzer können die Löschung dienstseitiger personenbezogener Informationen beim Support beantragen.",
        privacy_h9: "9. Sicherheit", privacy_p9: "Angemessene technische und organisatorische Maßnahmen werden eingesetzt oder geplant, um Informationen zu schützen. Kein System kann absolute Sicherheit garantieren. Nutzer bleiben für den Schutz ihres Geräts, ihrer Kontozugänge, Provider-Zugangsdaten und lokalen Sicherungen verantwortlich.",
        privacy_h10: "10. Internationale Verarbeitung", privacy_p10: "Dienstleister können Informationen in anderen Ländern als dem Land des Nutzers verarbeiten. Soweit gesetzlich erforderlich, werden geeignete Schutzmaßnahmen eingesetzt.",
        privacy_h11: "11. Nutzerrechte", privacy_p11: "Je nach Aufenthaltsort können Nutzer Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung oder Widerspruch gegen die Verarbeitung personenbezogener Informationen haben. Anfragen können gesendet werden an",
        privacy_h12: "12. Änderungen", privacy_p12: "Diese Erklärung kann aktualisiert werden, wenn die Produktionsarchitektur und Funktionen von Veylto fertiggestellt werden. Die neueste Version wird mit einem aktualisierten Datum auf dieser Seite veröffentlicht.",
        privacy_h13: "13. Kontakt", privacy_p13: "Fragen zum Datenschutz können gesendet werden an"
      }
    },
    terms: {
      en: {
        pageTitle: "Terms of Service — Veylto", metaDescription: "Veylto Terms of Service.", terms_title: "Terms of Service",
        terms_development: "Veylto is not yet publicly available. These terms are an initial framework for controlled testing and will be finalized before commercial release.",
        terms_h1: "1. Product status", terms_p1: "Veylto is AI-assisted desktop software developed under the independent Veylto Labs product brand and is currently in private development. Features, integrations, availability and system requirements may change before public release.",
        terms_h2: "2. Authorized use", terms_p2: "Users may use Veylto only for lawful seller workflows involving accounts, images, content and data they are authorized to access or process. Users must not use the software to scrape Etsy, bypass platform controls, interfere with services, misrepresent affiliation, infringe intellectual-property rights or violate third-party rights.",
        terms_h3: "3. Etsy connection", terms_p3: "Etsy access is provided through permissions granted by the seller. Users remain responsible for reviewing and confirming changes before they are applied to Etsy and for complying with Etsy’s terms, policies and seller obligations.",
        terms_h4: "4. No Etsy endorsement", terms_p4: "Veylto is an independent product. It is not endorsed, sponsored or certified by Etsy, Inc.",
        terms_h5: "5. AI-assisted output", terms_p5: "Veylto may analyze seller-provided product context, images and mockups and use the selected AI provider to generate listing drafts, SEO suggestions, social content and reports. AI-assisted output may be incomplete, inaccurate, inconsistent or unsuitable. Users must review titles, descriptions, tags, classifications, reports and other output before relying on, applying or publishing it. Veylto does not guarantee marketplace performance, ranking, traffic or sales.",
        terms_h6: "6. User responsibilities", terms_li61: "protect account access, devices, provider credentials and local files;", terms_li62: "maintain appropriate backups;", terms_li63: "verify listing, pricing, inventory, tax, shipping and policy information;", terms_li64: "obtain rights and permissions for uploaded, analyzed or generated content;", terms_li65: "comply with applicable laws and platform rules.",
        terms_h7: "7. Availability", terms_p7: "During development and testing, Veylto may be unavailable, interrupted or changed without notice. External services, AI providers and APIs may impose their own limits, terms or outages.",
        terms_h8: "8. Intellectual property", terms_p8: "Veylto, its interface, software, documentation and branding are protected by applicable intellectual-property laws. No ownership is transferred except for a limited right to use an authorized version of the software.",
        terms_h9: "9. Disclaimer", terms_p9: "To the maximum extent permitted by law, development versions are provided “as is” and “as available,” without warranties of uninterrupted operation, fitness for a particular purpose, error-free output or compatibility with every marketplace change.",
        terms_h10: "10. Limitation of liability", terms_p10: "To the maximum extent permitted by law, Veylto will not be liable for indirect, incidental, special or consequential loss, lost profits, lost data, provider failures, marketplace actions or decisions made from unreviewed output.",
        terms_h11: "11. Suspension and termination", terms_p11: "Access may be limited or terminated for security reasons, misuse, policy violations or discontinuation of a development program. Users may stop using the software and revoke connected access at any time.",
        terms_h12: "12. Changes", terms_p12: "These terms may be updated before and after release. Material changes will be reflected by the date shown at the top of this page.",
        terms_h13: "13. Contact", terms_p13: "Questions may be sent to"
      },
      it: {
        pageTitle: "Termini di servizio — Veylto", metaDescription: "Termini di servizio di Veylto.", terms_title: "Termini di servizio",
        terms_development: "Veylto non è ancora disponibile pubblicamente. Questi termini costituiscono un quadro iniziale per i test controllati e saranno completati prima del rilascio commerciale.",
        terms_h1: "1. Stato del prodotto", terms_p1: "Veylto è un software desktop assistito dall’AI sviluppato sotto il marchio di prodotto indipendente Veylto Labs ed è attualmente in sviluppo privato. Funzionalità, integrazioni, disponibilità e requisiti di sistema possono cambiare prima del rilascio pubblico.",
        terms_h2: "2. Uso autorizzato", terms_p2: "Gli utenti possono usare Veylto solo per workflow leciti di vendita che coinvolgano account, immagini, contenuti e dati che sono autorizzati ad accedere o trattare. Non è consentito usare il software per effettuare scraping di Etsy, aggirare i controlli della piattaforma, interferire con i servizi, dichiarare affiliazioni inesistenti, violare diritti di proprietà intellettuale o diritti di terzi.",
        terms_h3: "3. Collegamento a Etsy", terms_p3: "L’accesso a Etsy viene fornito tramite i permessi concessi dal venditore. Gli utenti restano responsabili della revisione e conferma delle modifiche prima che vengano applicate a Etsy e del rispetto dei termini, delle policy e degli obblighi del venditore Etsy.",
        terms_h4: "4. Nessuna approvazione da parte di Etsy", terms_p4: "Veylto è un prodotto indipendente. Non è approvato, sponsorizzato o certificato da Etsy, Inc.",
        terms_h5: "5. Output assistito dall’AI", terms_p5: "Veylto può analizzare contesto del prodotto, immagini e mockup forniti dal venditore e usare il provider AI selezionato per generare bozze di inserzioni, suggerimenti SEO, contenuti social e report. L’output assistito dall’AI può essere incompleto, inesatto, incoerente o inadatto. Gli utenti devono revisionare titoli, descrizioni, tag, classificazioni, report e altri output prima di utilizzarli, applicarli o pubblicarli. Veylto non garantisce prestazioni, posizionamento, traffico o vendite sul marketplace.",
        terms_h6: "6. Responsabilità dell’utente", terms_li61: "proteggere accesso agli account, dispositivi, credenziali dei provider e file locali;", terms_li62: "mantenere backup adeguati;", terms_li63: "verificare informazioni su inserzioni, prezzi, inventario, imposte, spedizioni e policy;", terms_li64: "ottenere diritti e autorizzazioni per contenuti caricati, analizzati o generati;", terms_li65: "rispettare le leggi applicabili e le regole delle piattaforme.",
        terms_h7: "7. Disponibilità", terms_p7: "Durante sviluppo e test, Veylto può essere indisponibile, interrotto o modificato senza preavviso. Servizi esterni, provider AI e API possono imporre limiti, termini o interruzioni propri.",
        terms_h8: "8. Proprietà intellettuale", terms_p8: "Veylto, la sua interfaccia, il software, la documentazione e il branding sono protetti dalle leggi applicabili sulla proprietà intellettuale. Non viene trasferita alcuna titolarità, salvo un diritto limitato a usare una versione autorizzata del software.",
        terms_h9: "9. Esclusione di garanzie", terms_p9: "Nella misura massima consentita dalla legge, le versioni di sviluppo sono fornite “così come sono” e “come disponibili”, senza garanzie di funzionamento ininterrotto, idoneità a uno scopo particolare, output privo di errori o compatibilità con ogni modifica del marketplace.",
        terms_h10: "10. Limitazione di responsabilità", terms_p10: "Nella misura massima consentita dalla legge, Veylto non sarà responsabile per perdite indirette, incidentali, speciali o consequenziali, mancati profitti, perdita di dati, errori dei provider, azioni del marketplace o decisioni prese sulla base di output non revisionati.",
        terms_h11: "11. Sospensione e cessazione", terms_p11: "L’accesso può essere limitato o interrotto per motivi di sicurezza, uso improprio, violazioni delle policy o cessazione di un programma di sviluppo. Gli utenti possono smettere di usare il software e revocare in qualsiasi momento gli accessi collegati.",
        terms_h12: "12. Modifiche", terms_p12: "Questi termini possono essere aggiornati prima e dopo il rilascio. Le modifiche sostanziali saranno indicate dalla data riportata in alto nella pagina.",
        terms_h13: "13. Contatti", terms_p13: "Le domande possono essere inviate a"
      },
      es: {
        pageTitle: "Términos del servicio — Veylto", metaDescription: "Términos del servicio de Veylto.", terms_title: "Términos del servicio",
        terms_development: "Veylto todavía no está disponible públicamente. Estos términos constituyen un marco inicial para pruebas controladas y se completarán antes del lanzamiento comercial.",
        terms_h1: "1. Estado del producto", terms_p1: "Veylto es un software de escritorio asistido por IA desarrollado bajo la marca de producto independiente Veylto Labs y actualmente se encuentra en desarrollo privado. Las funciones, integraciones, disponibilidad y requisitos del sistema pueden cambiar antes del lanzamiento público.",
        terms_h2: "2. Uso autorizado", terms_p2: "Los usuarios solo pueden utilizar Veylto para flujos legales de venta relacionados con cuentas, imágenes, contenidos y datos a los que estén autorizados a acceder o tratar. No deben utilizar el software para realizar scraping de Etsy, eludir controles de la plataforma, interferir con servicios, afirmar afiliaciones inexistentes, infringir derechos de propiedad intelectual o vulnerar derechos de terceros.",
        terms_h3: "3. Conexión con Etsy", terms_p3: "El acceso a Etsy se proporciona mediante los permisos concedidos por el vendedor. Los usuarios siguen siendo responsables de revisar y confirmar los cambios antes de aplicarlos a Etsy y de cumplir los términos, políticas y obligaciones del vendedor de Etsy.",
        terms_h4: "4. Sin respaldo de Etsy", terms_p4: "Veylto es un producto independiente. No está respaldado, patrocinado ni certificado por Etsy, Inc.",
        terms_h5: "5. Contenido asistido por IA", terms_p5: "Veylto puede analizar el contexto del producto, imágenes y mockups aportados por el vendedor y utilizar el proveedor de IA seleccionado para generar borradores, sugerencias SEO, contenido social e informes. El contenido asistido por IA puede ser incompleto, inexacto, incoherente o inadecuado. Los usuarios deben revisar títulos, descripciones, etiquetas, clasificaciones, informes y otros resultados antes de utilizarlos, aplicarlos o publicarlos. Veylto no garantiza rendimiento, posicionamiento, tráfico ni ventas en el marketplace.",
        terms_h6: "6. Responsabilidades del usuario", terms_li61: "proteger el acceso a cuentas, dispositivos, credenciales de proveedores y archivos locales;", terms_li62: "mantener copias de seguridad adecuadas;", terms_li63: "verificar información de publicaciones, precios, inventario, impuestos, envíos y políticas;", terms_li64: "obtener derechos y permisos para los contenidos cargados, analizados o generados;", terms_li65: "cumplir las leyes aplicables y las normas de las plataformas.",
        terms_h7: "7. Disponibilidad", terms_p7: "Durante el desarrollo y las pruebas, Veylto puede no estar disponible, sufrir interrupciones o cambiar sin previo aviso. Los servicios externos, proveedores de IA y API pueden imponer sus propios límites, términos o interrupciones.",
        terms_h8: "8. Propiedad intelectual", terms_p8: "Veylto, su interfaz, software, documentación y marca están protegidos por las leyes de propiedad intelectual aplicables. No se transfiere ninguna propiedad, salvo un derecho limitado a utilizar una versión autorizada del software.",
        terms_h9: "9. Exclusión de garantías", terms_p9: "En la máxima medida permitida por la ley, las versiones de desarrollo se proporcionan “tal cual” y “según disponibilidad”, sin garantías de funcionamiento ininterrumpido, idoneidad para un fin concreto, resultados sin errores o compatibilidad con todos los cambios del marketplace.",
        terms_h10: "10. Limitación de responsabilidad", terms_p10: "En la máxima medida permitida por la ley, Veylto no será responsable de pérdidas indirectas, incidentales, especiales o consecuentes, lucro cesante, pérdida de datos, fallos de proveedores, acciones del marketplace o decisiones tomadas a partir de resultados no revisados.",
        terms_h11: "11. Suspensión y finalización", terms_p11: "El acceso puede limitarse o finalizarse por motivos de seguridad, uso indebido, infracciones de políticas o finalización de un programa de desarrollo. Los usuarios pueden dejar de utilizar el software y revocar el acceso conectado en cualquier momento.",
        terms_h12: "12. Cambios", terms_p12: "Estos términos pueden actualizarse antes y después del lanzamiento. Los cambios sustanciales se reflejarán mediante la fecha indicada en la parte superior de esta página.",
        terms_h13: "13. Contacto", terms_p13: "Las preguntas pueden enviarse a"
      },
      fr: {
        pageTitle: "Conditions d’utilisation — Veylto", metaDescription: "Conditions d’utilisation de Veylto.", terms_title: "Conditions d’utilisation",
        terms_development: "Veylto n’est pas encore disponible publiquement. Ces conditions constituent un cadre initial pour des tests contrôlés et seront finalisées avant la commercialisation.",
        terms_h1: "1. État du produit", terms_p1: "Veylto est un logiciel desktop assisté par IA, développé sous la marque produit indépendante Veylto Labs et actuellement en développement privé. Les fonctionnalités, intégrations, disponibilités et exigences système peuvent évoluer avant la mise à disposition publique.",
        terms_h2: "2. Utilisation autorisée", terms_p2: "Les utilisateurs ne peuvent utiliser Veylto que pour des workflows vendeurs licites portant sur des comptes, images, contenus et données qu’ils sont autorisés à consulter ou traiter. Ils ne doivent pas utiliser le logiciel pour effectuer du scraping sur Etsy, contourner les contrôles de la plateforme, perturber les services, prétendre à une affiliation inexistante, enfreindre des droits de propriété intellectuelle ou violer les droits de tiers.",
        terms_h3: "3. Connexion à Etsy", terms_p3: "L’accès à Etsy repose sur les permissions accordées par le vendeur. Les utilisateurs restent responsables de la vérification et de la confirmation des modifications avant leur application à Etsy, ainsi que du respect des conditions, politiques et obligations vendeur d’Etsy.",
        terms_h4: "4. Absence d’approbation d’Etsy", terms_p4: "Veylto est un produit indépendant. Il n’est ni approuvé, ni sponsorisé, ni certifié par Etsy, Inc.",
        terms_h5: "5. Contenu assisté par IA", terms_p5: "Veylto peut analyser le contexte produit, les images et les mockups fournis par le vendeur et utiliser le fournisseur IA sélectionné pour générer des brouillons de fiches, suggestions SEO, contenus sociaux et rapports. Le contenu assisté par IA peut être incomplet, inexact, incohérent ou inadapté. Les utilisateurs doivent vérifier les titres, descriptions, tags, classifications, rapports et autres résultats avant de les utiliser, appliquer ou publier. Veylto ne garantit ni performance, ni classement, ni trafic, ni ventes sur la marketplace.",
        terms_h6: "6. Responsabilités de l’utilisateur", terms_li61: "protéger l’accès aux comptes, les appareils, les identifiants des fournisseurs et les fichiers locaux ;", terms_li62: "maintenir des sauvegardes appropriées ;", terms_li63: "vérifier les informations de fiche, prix, inventaire, fiscalité, expédition et politiques ;", terms_li64: "obtenir les droits et autorisations relatifs aux contenus importés, analysés ou générés ;", terms_li65: "respecter les lois applicables et les règles des plateformes.",
        terms_h7: "7. Disponibilité", terms_p7: "Pendant le développement et les tests, Veylto peut être indisponible, interrompu ou modifié sans préavis. Les services externes, fournisseurs IA et API peuvent imposer leurs propres limites, conditions ou interruptions.",
        terms_h8: "8. Propriété intellectuelle", terms_p8: "Veylto, son interface, son logiciel, sa documentation et son identité visuelle sont protégés par les lois applicables en matière de propriété intellectuelle. Aucun droit de propriété n’est transféré, à l’exception d’un droit limité d’utiliser une version autorisée du logiciel.",
        terms_h9: "9. Exclusion de garanties", terms_p9: "Dans toute la mesure permise par la loi, les versions de développement sont fournies « en l’état » et « selon disponibilité », sans garantie de fonctionnement ininterrompu, d’adéquation à un usage particulier, de résultat exempt d’erreur ou de compatibilité avec chaque évolution de la marketplace.",
        terms_h10: "10. Limitation de responsabilité", terms_p10: "Dans toute la mesure permise par la loi, Veylto ne sera pas responsable des pertes indirectes, accessoires, spéciales ou consécutives, pertes de bénéfices, pertes de données, défaillances des fournisseurs, actions de la marketplace ou décisions fondées sur des résultats non vérifiés.",
        terms_h11: "11. Suspension et résiliation", terms_p11: "L’accès peut être limité ou interrompu pour des raisons de sécurité, d’usage abusif, de violation des politiques ou d’arrêt d’un programme de développement. Les utilisateurs peuvent cesser d’utiliser le logiciel et révoquer les accès connectés à tout moment.",
        terms_h12: "12. Modifications", terms_p12: "Ces conditions peuvent être mises à jour avant et après le lancement. Les modifications importantes seront indiquées par la date figurant en haut de cette page.",
        terms_h13: "13. Contact", terms_p13: "Les questions peuvent être envoyées à"
      },
      de: {
        pageTitle: "Nutzungsbedingungen — Veylto", metaDescription: "Nutzungsbedingungen von Veylto.", terms_title: "Nutzungsbedingungen",
        terms_development: "Veylto ist noch nicht öffentlich verfügbar. Diese Bedingungen bilden einen ersten Rahmen für kontrollierte Tests und werden vor der kommerziellen Veröffentlichung fertiggestellt.",
        terms_h1: "1. Produktstatus", terms_p1: "Veylto ist KI-gestützte Desktop-Software, die unter der unabhängigen Produktmarke Veylto Labs entwickelt wird und sich derzeit in privater Entwicklung befindet. Funktionen, Integrationen, Verfügbarkeit und Systemanforderungen können sich vor der öffentlichen Veröffentlichung ändern.",
        terms_h2: "2. Autorisierte Nutzung", terms_p2: "Nutzer dürfen Veylto nur für rechtmäßige Seller-Workflows verwenden, die Konten, Bilder, Inhalte und Daten betreffen, auf die sie zugreifen oder die sie verarbeiten dürfen. Die Software darf nicht zum Scraping von Etsy, zur Umgehung von Plattformkontrollen, zur Störung von Diensten, zur falschen Darstellung einer Zugehörigkeit, zur Verletzung von Schutzrechten oder Rechten Dritter verwendet werden.",
        terms_h3: "3. Etsy-Verbindung", terms_p3: "Der Etsy-Zugriff erfolgt über vom Seller erteilte Berechtigungen. Nutzer bleiben dafür verantwortlich, Änderungen vor der Anwendung auf Etsy zu prüfen und zu bestätigen sowie die Etsy-Bedingungen, Richtlinien und Seller-Pflichten einzuhalten.",
        terms_h4: "4. Keine Unterstützung durch Etsy", terms_p4: "Veylto ist ein unabhängiges Produkt. Es wird nicht von Etsy, Inc. unterstützt, gesponsert oder zertifiziert.",
        terms_h5: "5. KI-gestützte Ausgabe", terms_p5: "Veylto kann vom Seller bereitgestellten Produktkontext, Bilder und Mockups analysieren und den ausgewählten KI-Provider verwenden, um Listing-Entwürfe, SEO-Vorschläge, Social Content und Berichte zu erzeugen. KI-gestützte Ausgaben können unvollständig, ungenau, inkonsistent oder ungeeignet sein. Nutzer müssen Titel, Beschreibungen, Tags, Klassifizierungen, Berichte und andere Ausgaben prüfen, bevor sie darauf vertrauen, sie anwenden oder veröffentlichen. Veylto garantiert keine Marketplace-Leistung, Rankings, Zugriffe oder Verkäufe.",
        terms_h6: "6. Pflichten der Nutzer", terms_li61: "Kontozugänge, Geräte, Provider-Zugangsdaten und lokale Dateien schützen;", terms_li62: "angemessene Sicherungen vorhalten;", terms_li63: "Listing-, Preis-, Inventar-, Steuer-, Versand- und Richtlinienangaben prüfen;", terms_li64: "Rechte und Berechtigungen für hochgeladene, analysierte oder erzeugte Inhalte einholen;", terms_li65: "anwendbare Gesetze und Plattformregeln einhalten.",
        terms_h7: "7. Verfügbarkeit", terms_p7: "Während Entwicklung und Tests kann Veylto ohne Vorankündigung nicht verfügbar, unterbrochen oder geändert werden. Externe Dienste, KI-Provider und APIs können eigene Grenzen, Bedingungen oder Ausfälle haben.",
        terms_h8: "8. Geistiges Eigentum", terms_p8: "Veylto, seine Benutzeroberfläche, Software, Dokumentation und Marke sind durch anwendbare Gesetze zum geistigen Eigentum geschützt. Es werden keine Eigentumsrechte übertragen, außer einem beschränkten Recht zur Nutzung einer autorisierten Softwareversion.",
        terms_h9: "9. Haftungsausschluss", terms_p9: "Soweit gesetzlich zulässig, werden Entwicklungsversionen „wie besehen“ und „wie verfügbar“ bereitgestellt, ohne Gewähr für unterbrechungsfreien Betrieb, Eignung für einen bestimmten Zweck, fehlerfreie Ausgabe oder Kompatibilität mit jeder Marketplace-Änderung.",
        terms_h10: "10. Haftungsbeschränkung", terms_p10: "Soweit gesetzlich zulässig, haftet Veylto nicht für indirekte, beiläufige, besondere oder Folgeschäden, entgangene Gewinne, Datenverlust, Provider-Ausfälle, Marketplace-Maßnahmen oder Entscheidungen auf Grundlage ungeprüfter Ausgaben.",
        terms_h11: "11. Sperrung und Beendigung", terms_p11: "Der Zugriff kann aus Sicherheitsgründen, wegen Missbrauchs, Richtlinienverstößen oder der Einstellung eines Entwicklungsprogramms eingeschränkt oder beendet werden. Nutzer können die Verwendung der Software beenden und verbundene Zugriffe jederzeit widerrufen.",
        terms_h12: "12. Änderungen", terms_p12: "Diese Bedingungen können vor und nach der Veröffentlichung aktualisiert werden. Wesentliche Änderungen werden durch das oben angezeigte Datum kenntlich gemacht.",
        terms_h13: "13. Kontakt", terms_p13: "Fragen können gesendet werden an"
      }
    }
  };

  const supportedLanguages = Object.keys(common);
  const page = document.body.dataset.legalPage || "privacy";
  const params = new URLSearchParams(window.location.search);
  const requestedLanguage = params.get("lang");
  const savedLanguage = window.localStorage.getItem("veylto-site-language");
  const browserLanguage = (navigator.language || "en").slice(0, 2).toLowerCase();
  const initialLanguage = supportedLanguages.includes(requestedLanguage)
    ? requestedLanguage
    : supportedLanguages.includes(savedLanguage)
      ? savedLanguage
      : supportedLanguages.includes(browserLanguage) ? browserLanguage : "en";

  const updateLocalizedLinks = (language) => {
    document.querySelectorAll("[data-localized-link]").forEach((link) => {
      const url = new URL(link.getAttribute("href"), window.location.href);
      if (language === "en") url.searchParams.delete("lang");
      else url.searchParams.set("lang", language);
      const filename = url.pathname.split("/").pop() || "index.html";
      link.setAttribute("href", `${filename}${url.search}${url.hash}`);
    });
  };

  const applyLanguage = (language) => {
    const dictionary = { ...common.en, ...pages[page].en, ...common[language], ...pages[page][language] };
    document.documentElement.lang = language;
    document.title = dictionary.pageTitle;
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) metaDescription.setAttribute("content", dictionary.metaDescription);
    document.querySelectorAll("[data-i18n]").forEach((node) => {
      const key = node.getAttribute("data-i18n");
      if (Object.prototype.hasOwnProperty.call(dictionary, key)) node.textContent = dictionary[key];
    });
    const selector = document.querySelector("#language-selector");
    if (selector) selector.value = language;
    updateLocalizedLinks(language);
    window.localStorage.setItem("veylto-site-language", language);
  };

  const selector = document.querySelector("#language-selector");
  if (selector) selector.addEventListener("change", (event) => {
    const language = event.target.value;
    applyLanguage(language);
    const url = new URL(window.location.href);
    if (language === "en") url.searchParams.delete("lang");
    else url.searchParams.set("lang", language);
    window.history.replaceState({}, "", url);
  });

  document.querySelectorAll("[data-year]").forEach((node) => { node.textContent = String(new Date().getFullYear()); });
  applyLanguage(initialLanguage);
})();
