(() => {
  const translations = {
    en: {
      pageTitle: 'Veylto — AI listing workflows for Etsy sellers',
      metaDescription: 'Veylto is AI-powered desktop software that turns product images and mockups into seller-reviewed Etsy listing drafts, SEO improvements, social content and market research.',
      skip: 'Skip to content', menu: 'Menu', language: 'Language', nav_ai: 'AI workflow', nav_product: 'Product', nav_principles: 'Principles', nav_security: 'Security', nav_privacy: 'Privacy', nav_terms: 'Terms',
      hero_eyebrow: 'Veylto Labs · AI desktop software for Etsy sellers', hero_title: 'From product images to Etsy-ready listing drafts.', hero_text: 'Veylto analyzes product images and mockups, generates titles, descriptions and tags with your selected AI provider, validates the result and keeps you in control before an Etsy draft is created.', hero_primary: 'See the AI workflow', hero_support: 'Contact support', availability: 'Early access reservations are open',
      mock_workspace: 'Veylto · AI Listing Generator', mock_section: 'AI LISTING WORKFLOW', mock_title: 'Build a listing from images', mock_status: 'Review required', mock_images: 'Images', mock_analyzed: 'Analyzed', mock_draft: 'AI draft', mock_generated: 'Generated', mock_validation: 'Validation', mock_passed: 'Passed', mock_result: 'Generated listing', mock_provider: 'Provider and model visible', mock_listing_title: 'Modern botanical wall art set for calm interiors', mock_review: 'Validate → Review → Create Etsy draft', mock_control: 'Seller controlled',
      ai_eyebrow: 'AI listing generation', ai_title: 'AI does the heavy work. You keep the final decision.', ai_intro: 'The selected product type, images and mockups guide the draft. Veylto then checks the output before any Etsy write action becomes available.',
      step_1_title: 'Provide product context', step_1_desc: 'Choose the physical or digital product type, seller details, product images and mockups.', step_2_title: 'Generate with AI', step_2_desc: 'Create a title, description, tags and listing content with the provider and model configured by the seller.', step_3_title: 'Validate the listing', step_3_desc: 'Check semantic consistency, product-type rules, prohibited wording and missing information.', step_4_title: 'Review before Etsy', step_4_desc: 'See the result, correct it when necessary and explicitly confirm creation of the Etsy draft.', provider_note_title: 'No silent AI switching.', provider_note_text: 'Veylto is designed to use the selected provider and model and to show that information with generated output.',
      product_eyebrow: 'One controlled workspace', product_title: 'More than a text generator.', product_intro: 'Veylto connects AI generation with the practical seller workflows that come before and after a listing draft.',
      feature_ai_title: 'AI Listing Generator', feature_ai_desc: 'Generate Etsy listing content from product context, images and mockups, then validate it before draft creation.', feature_seo_title: 'AI SEO review', feature_seo_desc: 'Compare current listing content with AI suggestions, scores and improvements before applying changes.', feature_etsy_title: 'Etsy workspace', feature_etsy_desc: 'Review shop data, prepare listings, manage drafts and keep every Etsy write action explicit.', feature_social_title: 'Social Studio', feature_social_desc: 'Generate platform-specific content and organize drafts, queue, publishing and history.', feature_market_title: 'Market intelligence', feature_market_desc: 'Structure research, evidence and reports to support product and seller decisions.', feature_control_title: 'Provider and local control', feature_control_desc: 'Keep provider, model, local data, AI drafts and Etsy-applied values clearly distinguishable.',
      principles_eyebrow: 'Product principles', principles_title: 'Automation should not hide consequences.', principle_review_title: 'Review before write', principle_review_desc: 'Changes that affect Etsy remain visible, confirmed and attributable.', principle_provider_title: 'The selected AI provider is the real provider', principle_provider_desc: 'Provider and model selection must be respected rather than silently replaced.', principle_boundaries_title: 'Clear data boundaries', principle_boundaries_desc: 'Local values, AI drafts, reviewed content and Etsy-applied values remain distinguishable.',
      security_eyebrow: 'Security and platform respect', security_title: 'Designed for authorized seller access.', security_intro: 'Veylto uses Etsy OAuth for permitted shop access. It does not scrape Etsy, request seller API credentials, bypass Etsy checkout or claim endorsement by Etsy.', security_link: 'Read the privacy policy →', security_oauth_title: 'OAuth authorization', security_oauth_desc: 'Access depends on permissions granted by the seller.', security_write_title: 'Explicit Etsy write actions', security_write_desc: 'Seller-impacting changes require a clear action, confirmation and progress feedback.', security_scraping_title: 'No scraping', security_scraping_desc: 'Platform data is accessed through supported interfaces.', security_revocable_title: 'Revocable access', security_revocable_desc: 'Connected access can be disconnected or revoked.',
      cta_eyebrow: 'Coming soon', cta_title: 'Veylto will soon be available to a selected group of Etsy sellers.', cta_text: 'Reserve your early access and receive updates about availability, pricing and launch.', cta_button: 'Reserve early access', early_access_subject: 'Veylto early access reservation', early_access_body: 'I would like to reserve early access to Veylto.', footer_tagline: 'AI-powered, local-first desktop software for Etsy seller workflows.', footer_brand_statement: 'Veylto is developed under the independent Veylto Labs product brand.', footer_privacy: 'Privacy Policy', footer_terms: 'Terms of Service', footer_support: 'Support', trademark: 'The term “Etsy” is a trademark of Etsy, Inc. This application uses the Etsy API but is not endorsed or certified by Etsy, Inc.'
    },
    it: {
      pageTitle: 'Veylto — Workflow AI per venditori Etsy',
      metaDescription: 'Veylto è un software desktop basato su AI che trasforma immagini e mockup di prodotto in bozze Etsy controllate dal venditore, revisioni SEO, contenuti social e analisi di mercato.',
      skip: 'Vai al contenuto', menu: 'Menu', language: 'Lingua', nav_ai: 'Workflow AI', nav_product: 'Prodotto', nav_principles: 'Principi', nav_security: 'Sicurezza', nav_privacy: 'Privacy', nav_terms: 'Termini',
      hero_eyebrow: 'Veylto Labs · Software desktop AI per venditori Etsy', hero_title: 'Dalle immagini del prodotto a una bozza Etsy pronta da revisionare.', hero_text: 'Veylto analizza immagini e mockup, genera titolo, descrizione e tag con il provider AI selezionato, valida il risultato e lascia a te il controllo prima della creazione della bozza Etsy.', hero_primary: 'Scopri il workflow AI', hero_support: 'Contatta il supporto', availability: 'Prenotazioni per l’accesso anticipato aperte',
      mock_workspace: 'Veylto · Generatore inserzioni AI', mock_section: 'WORKFLOW INSERZIONE AI', mock_title: 'Crea un’inserzione dalle immagini', mock_status: 'Revisione richiesta', mock_images: 'Immagini', mock_analyzed: 'Analizzate', mock_draft: 'Bozza AI', mock_generated: 'Generata', mock_validation: 'Validazione', mock_passed: 'Superata', mock_result: 'Inserzione generata', mock_provider: 'Provider e modello visibili', mock_listing_title: 'Set di stampe botaniche moderne per interni rilassanti', mock_review: 'Valida → Revisiona → Crea bozza Etsy', mock_control: 'Controllo del venditore',
      ai_eyebrow: 'Generazione inserzioni con AI', ai_title: 'L’AI svolge il lavoro pesante. La decisione finale resta a te.', ai_intro: 'Tipo di prodotto, immagini e mockup guidano la bozza. Veylto controlla poi l’output prima di rendere disponibile qualsiasi scrittura su Etsy.',
      step_1_title: 'Fornisci il contesto del prodotto', step_1_desc: 'Scegli prodotto fisico o digitale, dati del venditore, immagini e mockup.', step_2_title: 'Genera con l’AI', step_2_desc: 'Crea titolo, descrizione, tag e contenuto dell’inserzione con provider e modello configurati dal venditore.', step_3_title: 'Valida l’inserzione', step_3_desc: 'Controlla coerenza semantica, regole del tipo di prodotto, espressioni vietate e dati mancanti.', step_4_title: 'Revisiona prima di Etsy', step_4_desc: 'Esamina il risultato, correggilo quando necessario e conferma esplicitamente la creazione della bozza Etsy.', provider_note_title: 'Nessun cambio silenzioso dell’AI.', provider_note_text: 'Veylto è progettato per usare il provider e il modello selezionati e mostrarli insieme all’output generato.',
      product_eyebrow: 'Un unico workspace controllato', product_title: 'Molto più di un generatore di testi.', product_intro: 'Veylto collega la generazione AI ai workflow concreti che precedono e seguono la bozza di un’inserzione.',
      feature_ai_title: 'Generatore inserzioni AI', feature_ai_desc: 'Genera contenuti Etsy da contesto, immagini e mockup, quindi validali prima della creazione della bozza.', feature_seo_title: 'Revisione SEO con AI', feature_seo_desc: 'Confronta i contenuti attuali con suggerimenti, punteggi e miglioramenti AI prima di applicare modifiche.', feature_etsy_title: 'Workspace Etsy', feature_etsy_desc: 'Controlla i dati del negozio, prepara inserzioni, gestisci bozze e mantieni esplicita ogni scrittura su Etsy.', feature_social_title: 'Social Studio', feature_social_desc: 'Genera contenuti specifici per piattaforma e organizza bozze, coda, pubblicazione e cronologia.', feature_market_title: 'Analisi di mercato', feature_market_desc: 'Struttura ricerca, evidenze e report per supportare decisioni su prodotti e negozio.', feature_control_title: 'Controllo provider e dati locali', feature_control_desc: 'Mantieni distinguibili provider, modello, dati locali, bozze AI e valori applicati a Etsy.',
      principles_eyebrow: 'Principi del prodotto', principles_title: 'L’automazione non deve nascondere le conseguenze.', principle_review_title: 'Revisione prima della scrittura', principle_review_desc: 'Le modifiche che interessano Etsy restano visibili, confermate e attribuibili.', principle_provider_title: 'Il provider AI selezionato è quello realmente usato', principle_provider_desc: 'La scelta di provider e modello deve essere rispettata, senza sostituzioni silenziose.', principle_boundaries_title: 'Confini dei dati chiari', principle_boundaries_desc: 'Valori locali, bozze AI, contenuti revisionati e valori applicati a Etsy restano distinguibili.',
      security_eyebrow: 'Sicurezza e rispetto della piattaforma', security_title: 'Progettato per l’accesso autorizzato del venditore.', security_intro: 'Veylto usa Etsy OAuth per l’accesso autorizzato al negozio. Non esegue scraping, non richiede credenziali API del venditore, non aggira il checkout Etsy e non dichiara approvazione da parte di Etsy.', security_link: 'Leggi l’informativa privacy →', security_oauth_title: 'Autorizzazione OAuth', security_oauth_desc: 'L’accesso dipende dai permessi concessi dal venditore.', security_write_title: 'Scritture Etsy esplicite', security_write_desc: 'Le modifiche che incidono sul venditore richiedono azione chiara, conferma e stato di avanzamento.', security_scraping_title: 'Nessuno scraping', security_scraping_desc: 'I dati della piattaforma vengono acquisiti tramite interfacce supportate.', security_revocable_title: 'Accesso revocabile', security_revocable_desc: 'L’accesso collegato può essere disconnesso o revocato.',
      cta_eyebrow: 'Disponibile a breve', cta_title: 'Veylto sarà presto disponibile per un gruppo selezionato di venditori Etsy.', cta_text: 'Prenota gratuitamente il tuo accesso anticipato e ricevi aggiornamenti su disponibilità, prezzi e lancio.', cta_button: 'Prenota l’accesso anticipato', early_access_subject: 'Prenotazione accesso anticipato Veylto', early_access_body: 'Vorrei prenotare l’accesso anticipato a Veylto.', footer_tagline: 'Software desktop local-first basato su AI per i workflow dei venditori Etsy.', footer_brand_statement: 'Veylto è sviluppato sotto il marchio di prodotto indipendente Veylto Labs.', footer_privacy: 'Informativa privacy', footer_terms: 'Termini di servizio', footer_support: 'Supporto', trademark: 'Il termine “Etsy” è un marchio di Etsy, Inc. Questa applicazione utilizza l’API di Etsy, ma non è approvata né certificata da Etsy, Inc.'
    },
    es: {
      pageTitle: 'Veylto — Flujos de IA para vendedores de Etsy',
      metaDescription: 'Veylto es un software de escritorio con IA que convierte imágenes y mockups de producto en borradores de Etsy revisados por el vendedor, mejoras SEO, contenido social e investigación de mercado.',
      skip: 'Ir al contenido', menu: 'Menú', language: 'Idioma', nav_ai: 'Flujo de IA', nav_product: 'Producto', nav_principles: 'Principios', nav_security: 'Seguridad', nav_privacy: 'Privacidad', nav_terms: 'Términos',
      hero_eyebrow: 'Veylto Labs · Software de escritorio con IA para vendedores de Etsy', hero_title: 'De las imágenes del producto a un borrador de Etsy listo para revisar.', hero_text: 'Veylto analiza imágenes y mockups, genera título, descripción y etiquetas con el proveedor de IA seleccionado, valida el resultado y mantiene tu control antes de crear el borrador de Etsy.', hero_primary: 'Ver el flujo de IA', hero_support: 'Contactar con soporte', availability: 'Reservas de acceso anticipado abiertas',
      mock_workspace: 'Veylto · Generador de publicaciones con IA', mock_section: 'FLUJO DE PUBLICACIÓN CON IA', mock_title: 'Crear una publicación desde imágenes', mock_status: 'Revisión necesaria', mock_images: 'Imágenes', mock_analyzed: 'Analizadas', mock_draft: 'Borrador IA', mock_generated: 'Generado', mock_validation: 'Validación', mock_passed: 'Superada', mock_result: 'Publicación generada', mock_provider: 'Proveedor y modelo visibles', mock_listing_title: 'Set de arte botánico moderno para interiores tranquilos', mock_review: 'Validar → Revisar → Crear borrador Etsy', mock_control: 'Control del vendedor',
      ai_eyebrow: 'Generación de publicaciones con IA', ai_title: 'La IA realiza el trabajo pesado. Tú conservas la decisión final.', ai_intro: 'El tipo de producto, las imágenes y los mockups guían el borrador. Veylto comprueba el resultado antes de habilitar cualquier escritura en Etsy.',
      step_1_title: 'Aporta el contexto del producto', step_1_desc: 'Elige producto físico o digital, datos del vendedor, imágenes y mockups.', step_2_title: 'Genera con IA', step_2_desc: 'Crea título, descripción, etiquetas y contenido con el proveedor y modelo configurados por el vendedor.', step_3_title: 'Valida la publicación', step_3_desc: 'Comprueba coherencia semántica, reglas del tipo de producto, expresiones prohibidas e información ausente.', step_4_title: 'Revisa antes de Etsy', step_4_desc: 'Examina el resultado, corrígelo cuando sea necesario y confirma expresamente la creación del borrador.', provider_note_title: 'Sin cambios silenciosos de IA.', provider_note_text: 'Veylto está diseñado para usar el proveedor y modelo seleccionados y mostrarlos con el contenido generado.',
      product_eyebrow: 'Un espacio de trabajo controlado', product_title: 'Mucho más que un generador de texto.', product_intro: 'Veylto conecta la generación con IA con los flujos reales que preceden y siguen a un borrador.',
      feature_ai_title: 'Generador de publicaciones con IA', feature_ai_desc: 'Genera contenido para Etsy a partir del contexto, imágenes y mockups, y valídalo antes de crear el borrador.', feature_seo_title: 'Revisión SEO con IA', feature_seo_desc: 'Compara el contenido actual con sugerencias, puntuaciones y mejoras de IA antes de aplicar cambios.', feature_etsy_title: 'Espacio Etsy', feature_etsy_desc: 'Revisa datos de la tienda, prepara publicaciones, gestiona borradores y mantén explícita cada escritura en Etsy.', feature_social_title: 'Social Studio', feature_social_desc: 'Genera contenido específico para cada plataforma y organiza borradores, cola, publicación e historial.', feature_market_title: 'Inteligencia de mercado', feature_market_desc: 'Estructura investigación, evidencias e informes para apoyar decisiones de producto y tienda.', feature_control_title: 'Control del proveedor y datos locales', feature_control_desc: 'Distingue claramente proveedor, modelo, datos locales, borradores de IA y valores aplicados a Etsy.',
      principles_eyebrow: 'Principios del producto', principles_title: 'La automatización no debe ocultar las consecuencias.', principle_review_title: 'Revisar antes de escribir', principle_review_desc: 'Los cambios que afectan a Etsy permanecen visibles, confirmados y atribuibles.', principle_provider_title: 'El proveedor de IA seleccionado es el utilizado', principle_provider_desc: 'La selección de proveedor y modelo debe respetarse sin sustituciones silenciosas.', principle_boundaries_title: 'Límites de datos claros', principle_boundaries_desc: 'Valores locales, borradores de IA, contenido revisado y valores aplicados a Etsy siguen diferenciados.',
      security_eyebrow: 'Seguridad y respeto a la plataforma', security_title: 'Diseñado para acceso autorizado del vendedor.', security_intro: 'Veylto utiliza Etsy OAuth para el acceso permitido a la tienda. No realiza scraping, no solicita credenciales API del vendedor, no elude el pago de Etsy ni afirma estar respaldado por Etsy.', security_link: 'Leer la política de privacidad →', security_oauth_title: 'Autorización OAuth', security_oauth_desc: 'El acceso depende de los permisos concedidos por el vendedor.', security_write_title: 'Escrituras en Etsy explícitas', security_write_desc: 'Los cambios que afectan al vendedor requieren una acción clara, confirmación e información de progreso.', security_scraping_title: 'Sin scraping', security_scraping_desc: 'Los datos se obtienen mediante interfaces compatibles.', security_revocable_title: 'Acceso revocable', security_revocable_desc: 'El acceso conectado puede desconectarse o revocarse.',
      cta_eyebrow: 'Próximamente', cta_title: 'Veylto estará disponible pronto para un grupo seleccionado de vendedores de Etsy.', cta_text: 'Reserva gratuitamente tu acceso anticipado y recibe novedades sobre disponibilidad, precios y lanzamiento.', cta_button: 'Reservar acceso anticipado', early_access_subject: 'Reserva de acceso anticipado a Veylto', early_access_body: 'Quiero reservar el acceso anticipado a Veylto.', footer_tagline: 'Software de escritorio local-first con IA para flujos de vendedores de Etsy.', footer_brand_statement: 'Veylto se desarrolla bajo la marca de producto independiente Veylto Labs.', footer_privacy: 'Política de privacidad', footer_terms: 'Términos del servicio', footer_support: 'Soporte', trademark: 'El término “Etsy” es una marca comercial de Etsy, Inc. Esta aplicación utiliza la API de Etsy, pero no está respaldada ni certificada por Etsy, Inc.'
    },
    fr: {
      pageTitle: 'Veylto — Workflows IA pour vendeurs Etsy',
      metaDescription: 'Veylto est un logiciel desktop alimenté par l’IA qui transforme images et mockups produit en brouillons Etsy vérifiés par le vendeur, améliorations SEO, contenus sociaux et études de marché.',
      skip: 'Aller au contenu', menu: 'Menu', language: 'Langue', nav_ai: 'Workflow IA', nav_product: 'Produit', nav_principles: 'Principes', nav_security: 'Sécurité', nav_privacy: 'Confidentialité', nav_terms: 'Conditions',
      hero_eyebrow: 'Veylto Labs · Logiciel desktop IA pour vendeurs Etsy', hero_title: 'Des images produit à un brouillon Etsy prêt à être vérifié.', hero_text: 'Veylto analyse les images et mockups, génère titre, description et tags avec le fournisseur IA sélectionné, valide le résultat et vous laisse le contrôle avant la création du brouillon Etsy.', hero_primary: 'Voir le workflow IA', hero_support: 'Contacter le support', availability: 'Réservations pour l’accès anticipé ouvertes',
      mock_workspace: 'Veylto · Générateur de fiches IA', mock_section: 'WORKFLOW DE FICHE IA', mock_title: 'Créer une fiche à partir d’images', mock_status: 'Vérification requise', mock_images: 'Images', mock_analyzed: 'Analysées', mock_draft: 'Brouillon IA', mock_generated: 'Généré', mock_validation: 'Validation', mock_passed: 'Réussie', mock_result: 'Fiche générée', mock_provider: 'Fournisseur et modèle visibles', mock_listing_title: 'Ensemble d’affiches botaniques modernes pour intérieur apaisant', mock_review: 'Valider → Vérifier → Créer le brouillon Etsy', mock_control: 'Contrôle vendeur',
      ai_eyebrow: 'Génération de fiches par IA', ai_title: 'L’IA effectue le travail lourd. Vous gardez la décision finale.', ai_intro: 'Le type de produit, les images et les mockups guident le brouillon. Veylto vérifie ensuite le résultat avant toute action d’écriture sur Etsy.',
      step_1_title: 'Fournir le contexte produit', step_1_desc: 'Choisissez le type physique ou numérique, les informations vendeur, les images et les mockups.', step_2_title: 'Générer avec l’IA', step_2_desc: 'Créez titre, description, tags et contenu avec le fournisseur et le modèle configurés par le vendeur.', step_3_title: 'Valider la fiche', step_3_desc: 'Contrôlez la cohérence sémantique, les règles du type de produit, les formulations interdites et les informations manquantes.', step_4_title: 'Vérifier avant Etsy', step_4_desc: 'Examinez le résultat, corrigez-le si nécessaire et confirmez explicitement la création du brouillon Etsy.', provider_note_title: 'Aucun changement silencieux d’IA.', provider_note_text: 'Veylto est conçu pour utiliser le fournisseur et le modèle sélectionnés et les afficher avec le contenu généré.',
      product_eyebrow: 'Un espace de travail contrôlé', product_title: 'Bien plus qu’un générateur de texte.', product_intro: 'Veylto relie la génération IA aux workflows concrets qui précèdent et suivent un brouillon de fiche.',
      feature_ai_title: 'Générateur de fiches IA', feature_ai_desc: 'Générez du contenu Etsy à partir du contexte, des images et des mockups, puis validez-le avant le brouillon.', feature_seo_title: 'Audit SEO par IA', feature_seo_desc: 'Comparez le contenu actuel aux suggestions, scores et améliorations IA avant toute modification.', feature_etsy_title: 'Espace Etsy', feature_etsy_desc: 'Consultez les données boutique, préparez les fiches, gérez les brouillons et gardez explicite chaque écriture Etsy.', feature_social_title: 'Social Studio', feature_social_desc: 'Générez du contenu par plateforme et organisez brouillons, file, publication et historique.', feature_market_title: 'Étude de marché', feature_market_desc: 'Structurez recherche, preuves et rapports pour soutenir les décisions produit et boutique.', feature_control_title: 'Contrôle du fournisseur et des données locales', feature_control_desc: 'Distinguez clairement fournisseur, modèle, données locales, brouillons IA et valeurs appliquées à Etsy.',
      principles_eyebrow: 'Principes du produit', principles_title: 'L’automatisation ne doit pas masquer les conséquences.', principle_review_title: 'Vérifier avant d’écrire', principle_review_desc: 'Les changements qui affectent Etsy restent visibles, confirmés et attribuables.', principle_provider_title: 'Le fournisseur IA sélectionné est réellement utilisé', principle_provider_desc: 'Le choix du fournisseur et du modèle doit être respecté sans substitution silencieuse.', principle_boundaries_title: 'Frontières de données claires', principle_boundaries_desc: 'Valeurs locales, brouillons IA, contenu vérifié et valeurs appliquées à Etsy restent distincts.',
      security_eyebrow: 'Sécurité et respect de la plateforme', security_title: 'Conçu pour un accès vendeur autorisé.', security_intro: 'Veylto utilise Etsy OAuth pour l’accès autorisé à la boutique. Il ne collecte pas les données par scraping, ne demande pas les identifiants API du vendeur, ne contourne pas le paiement Etsy et ne prétend pas être approuvé par Etsy.', security_link: 'Lire la politique de confidentialité →', security_oauth_title: 'Autorisation OAuth', security_oauth_desc: 'L’accès dépend des permissions accordées par le vendeur.', security_write_title: 'Écritures Etsy explicites', security_write_desc: 'Les changements ayant un impact vendeur exigent une action claire, une confirmation et un suivi de progression.', security_scraping_title: 'Aucun scraping', security_scraping_desc: 'Les données de la plateforme sont obtenues via des interfaces prises en charge.', security_revocable_title: 'Accès révocable', security_revocable_desc: 'L’accès connecté peut être déconnecté ou révoqué.',
      cta_eyebrow: 'Bientôt disponible', cta_title: 'Veylto sera bientôt disponible pour un groupe sélectionné de vendeurs Etsy.', cta_text: 'Réservez gratuitement votre accès anticipé et recevez les informations sur la disponibilité, les tarifs et le lancement.', cta_button: 'Réserver l’accès anticipé', early_access_subject: 'Réservation de l’accès anticipé à Veylto', early_access_body: 'Je souhaite réserver l’accès anticipé à Veylto.', footer_tagline: 'Logiciel desktop local-first alimenté par l’IA pour les workflows vendeurs Etsy.', footer_brand_statement: 'Veylto est développé sous la marque produit indépendante Veylto Labs.', footer_privacy: 'Politique de confidentialité', footer_terms: 'Conditions d’utilisation', footer_support: 'Support', trademark: 'Le terme « Etsy » est une marque d’Etsy, Inc. Cette application utilise l’API Etsy mais n’est ni approuvée ni certifiée par Etsy, Inc.'
    },
    de: {
      pageTitle: 'Veylto — KI-Workflows für Etsy-Seller',
      metaDescription: 'Veylto ist KI-gestützte Desktop-Software, die Produktbilder und Mockups in vom Seller geprüfte Etsy-Entwürfe, SEO-Verbesserungen, Social Content und Marktanalysen verwandelt.',
      skip: 'Zum Inhalt', menu: 'Menü', language: 'Sprache', nav_ai: 'KI-Workflow', nav_product: 'Produkt', nav_principles: 'Prinzipien', nav_security: 'Sicherheit', nav_privacy: 'Datenschutz', nav_terms: 'Bedingungen',
      hero_eyebrow: 'Veylto Labs · KI-Desktop-Software für Etsy-Seller', hero_title: 'Von Produktbildern zum prüfbereiten Etsy-Entwurf.', hero_text: 'Veylto analysiert Produktbilder und Mockups, erzeugt Titel, Beschreibung und Tags mit dem gewählten KI-Provider, validiert das Ergebnis und lässt die Kontrolle vor dem Etsy-Entwurf beim Seller.', hero_primary: 'KI-Workflow ansehen', hero_support: 'Support kontaktieren', availability: 'Reservierungen für den frühen Zugang sind geöffnet',
      mock_workspace: 'Veylto · KI-Listing-Generator', mock_section: 'KI-LISTING-WORKFLOW', mock_title: 'Listing aus Bildern erstellen', mock_status: 'Prüfung erforderlich', mock_images: 'Bilder', mock_analyzed: 'Analysiert', mock_draft: 'KI-Entwurf', mock_generated: 'Erzeugt', mock_validation: 'Validierung', mock_passed: 'Bestanden', mock_result: 'Erzeugtes Listing', mock_provider: 'Provider und Modell sichtbar', mock_listing_title: 'Modernes botanisches Wandbild-Set für ruhige Räume', mock_review: 'Validieren → Prüfen → Etsy-Entwurf erstellen', mock_control: 'Seller kontrolliert',
      ai_eyebrow: 'KI-Listing-Erstellung', ai_title: 'Die KI übernimmt die schwere Arbeit. Die letzte Entscheidung bleibt bei Ihnen.', ai_intro: 'Produkttyp, Bilder und Mockups steuern den Entwurf. Veylto prüft die Ausgabe, bevor eine Etsy-Schreibaktion verfügbar wird.',
      step_1_title: 'Produktkontext bereitstellen', step_1_desc: 'Wählen Sie physischen oder digitalen Produkttyp, Seller-Angaben, Bilder und Mockups.', step_2_title: 'Mit KI erzeugen', step_2_desc: 'Erstellen Sie Titel, Beschreibung, Tags und Listing-Inhalt mit dem vom Seller konfigurierten Provider und Modell.', step_3_title: 'Listing validieren', step_3_desc: 'Prüfen Sie semantische Konsistenz, Produkttyp-Regeln, verbotene Formulierungen und fehlende Angaben.', step_4_title: 'Vor Etsy prüfen', step_4_desc: 'Prüfen und korrigieren Sie das Ergebnis und bestätigen Sie ausdrücklich die Erstellung des Etsy-Entwurfs.', provider_note_title: 'Kein stiller KI-Wechsel.', provider_note_text: 'Veylto ist darauf ausgelegt, den gewählten Provider und das Modell zu verwenden und mit der Ausgabe anzuzeigen.',
      product_eyebrow: 'Ein kontrollierter Arbeitsbereich', product_title: 'Mehr als ein Textgenerator.', product_intro: 'Veylto verbindet KI-Erstellung mit den praktischen Seller-Workflows vor und nach einem Listing-Entwurf.',
      feature_ai_title: 'KI-Listing-Generator', feature_ai_desc: 'Erzeugen Sie Etsy-Inhalte aus Produktkontext, Bildern und Mockups und validieren Sie sie vor dem Entwurf.', feature_seo_title: 'KI-SEO-Prüfung', feature_seo_desc: 'Vergleichen Sie aktuelle Inhalte mit KI-Vorschlägen, Scores und Verbesserungen, bevor Änderungen angewendet werden.', feature_etsy_title: 'Etsy-Arbeitsbereich', feature_etsy_desc: 'Prüfen Sie Shop-Daten, bereiten Sie Listings vor, verwalten Sie Entwürfe und halten Sie jede Etsy-Schreibaktion ausdrücklich.', feature_social_title: 'Social Studio', feature_social_desc: 'Erzeugen Sie plattformspezifische Inhalte und organisieren Sie Entwürfe, Warteschlange, Veröffentlichung und Historie.', feature_market_title: 'Marktanalysen', feature_market_desc: 'Strukturieren Sie Recherche, Belege und Berichte für Produkt- und Shop-Entscheidungen.', feature_control_title: 'Provider- und lokale Kontrolle', feature_control_desc: 'Halten Sie Provider, Modell, lokale Daten, KI-Entwürfe und Etsy-Werte klar unterscheidbar.',
      principles_eyebrow: 'Produktprinzipien', principles_title: 'Automatisierung darf Folgen nicht verbergen.', principle_review_title: 'Prüfen vor dem Schreiben', principle_review_desc: 'Etsy-relevante Änderungen bleiben sichtbar, bestätigt und nachvollziehbar.', principle_provider_title: 'Der gewählte KI-Provider wird tatsächlich verwendet', principle_provider_desc: 'Provider- und Modellwahl müssen ohne stillen Ersatz respektiert werden.', principle_boundaries_title: 'Klare Datengrenzen', principle_boundaries_desc: 'Lokale Werte, KI-Entwürfe, geprüfte Inhalte und Etsy-Werte bleiben unterscheidbar.',
      security_eyebrow: 'Sicherheit und Plattformrespekt', security_title: 'Für autorisierten Seller-Zugriff entwickelt.', security_intro: 'Veylto nutzt Etsy OAuth für erlaubten Shop-Zugriff. Es betreibt kein Scraping, verlangt keine Seller-API-Zugangsdaten, umgeht nicht den Etsy-Checkout und behauptet keine Unterstützung durch Etsy.', security_link: 'Datenschutzerklärung lesen →', security_oauth_title: 'OAuth-Autorisierung', security_oauth_desc: 'Der Zugriff basiert auf den vom Seller erteilten Berechtigungen.', security_write_title: 'Explizite Etsy-Schreibaktionen', security_write_desc: 'Seller-relevante Änderungen erfordern eine klare Aktion, Bestätigung und Fortschrittsanzeige.', security_scraping_title: 'Kein Scraping', security_scraping_desc: 'Plattformdaten werden über unterstützte Schnittstellen abgerufen.', security_revocable_title: 'Widerrufbarer Zugriff', security_revocable_desc: 'Verbundener Zugriff kann getrennt oder widerrufen werden.',
      cta_eyebrow: 'Demnächst verfügbar', cta_title: 'Veylto wird bald für eine ausgewählte Gruppe von Etsy-Sellern verfügbar sein.', cta_text: 'Reservieren Sie kostenlos Ihren frühen Zugang und erhalten Sie Informationen zu Verfügbarkeit, Preisen und Start.', cta_button: 'Frühen Zugang reservieren', early_access_subject: 'Reservierung des frühen Zugangs zu Veylto', early_access_body: 'Ich möchte den frühen Zugang zu Veylto reservieren.', footer_tagline: 'KI-gestützte Local-first-Desktop-Software für Etsy-Seller-Workflows.', footer_brand_statement: 'Veylto wird unter der unabhängigen Produktmarke Veylto Labs entwickelt.', footer_privacy: 'Datenschutzerklärung', footer_terms: 'Nutzungsbedingungen', footer_support: 'Support', trademark: 'Der Begriff „Etsy“ ist eine Marke von Etsy, Inc. Diese Anwendung verwendet die Etsy-API, wird jedoch nicht von Etsy, Inc. unterstützt oder zertifiziert.'
    }
  };

  const supportedLanguages = Object.keys(translations);
  const params = new URLSearchParams(window.location.search);
  const requestedLanguage = params.get('lang');
  const savedLanguage = window.localStorage.getItem('veylto-site-language');
  const browserLanguage = (navigator.language || 'en').slice(0, 2).toLowerCase();
  const initialLanguage = supportedLanguages.includes(requestedLanguage)
    ? requestedLanguage
    : supportedLanguages.includes(savedLanguage)
      ? savedLanguage
      : supportedLanguages.includes(browserLanguage) ? browserLanguage : 'en';

  const updateLocalizedLinks = (language) => {
    document.querySelectorAll('[data-localized-link]').forEach((link) => {
      const url = new URL(link.getAttribute('href'), window.location.href);
      if (language === 'en') url.searchParams.delete('lang');
      else url.searchParams.set('lang', language);
      link.setAttribute('href', `${url.pathname.split('/').pop()}${url.search}`);
    });
  };

  const applyLanguage = (language) => {
    const dictionary = translations[language] || translations.en;
    document.documentElement.lang = language;
    document.title = dictionary.pageTitle;
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) metaDescription.setAttribute('content', dictionary.metaDescription);
    document.querySelectorAll('[data-i18n]').forEach((node) => {
      const key = node.getAttribute('data-i18n');
      if (Object.prototype.hasOwnProperty.call(dictionary, key)) node.textContent = dictionary[key];
    });
    const earlyAccessLink = document.querySelector('#early-access-link');
    if (earlyAccessLink) {
      const subject = encodeURIComponent(dictionary.early_access_subject);
      const body = encodeURIComponent(dictionary.early_access_body);
      earlyAccessLink.setAttribute('href', `mailto:support@veyltolabs.com?subject=${subject}&body=${body}`);
    }
    const selector = document.querySelector('#language-selector');
    if (selector) selector.value = language;
    updateLocalizedLinks(language);
    window.localStorage.setItem('veylto-site-language', language);
  };

  const selector = document.querySelector('#language-selector');
  if (selector) selector.addEventListener('change', (event) => {
    const language = event.target.value;
    applyLanguage(language);
    const url = new URL(window.location.href);
    if (language === 'en') url.searchParams.delete('lang');
    else url.searchParams.set('lang', language);
    window.history.replaceState({}, '', url);
  });

  const menuButton = document.querySelector('.menu-button');
  const nav = document.querySelector('#primary-nav');
  if (menuButton && nav) {
    menuButton.addEventListener('click', () => {
      const open = menuButton.getAttribute('aria-expanded') === 'true';
      menuButton.setAttribute('aria-expanded', String(!open));
      nav.classList.toggle('is-open', !open);
    });
    nav.querySelectorAll('a').forEach((link) => link.addEventListener('click', () => {
      menuButton.setAttribute('aria-expanded', 'false');
      nav.classList.remove('is-open');
    }));
  }

  document.querySelectorAll('[data-year]').forEach((node) => { node.textContent = String(new Date().getFullYear()); });
  applyLanguage(initialLanguage);
})();